moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager
allowed_execution_duration_scaling: 1.2
allowed_goal_duration_margin: 0.5
allowed_start_tolerance: 0.01
trajectory_execution:
  allowed_execution_duration_scaling: 1.2
  allowed_goal_duration_margin: 0.5
  allowed_start_tolerance: 0.01
  wait_for_trajectory_completion: true
plan_execution:
  max_replan_attempts: 10
  record_trajectory_state_frequency: 0.0

